### ISSUE TITLE
Align the UI/Theme to unet's webite.

### ISSUE THREAD

**Issue by notthetup** [notthetup/unet-blog#1]
http://www.unetstack.net/

**Comment by sayanee** [comment]
Design inspirations:

- [pytorch](https://pytorch.org/)

**Comment by sayanee** [comment]
# Todo

- [ ] change color in the top nav bar to black
- [ ] expand the height of the homepage hero section
- [ ] insert slight node interactive animation in the homepage hero section
- [ ] remove `text-shadow` for headings
- [ ] change posts' tag position from bottom to top
- [ ] add search bar on the home page
