### ISSUE TITLE
Align Search page's header to homepage

### ISSUE THREAD

**Issue by sayanee** [notthetup/unet-blog#3]
![image](https://user-images.githubusercontent.com/413879/44987664-89793500-afba-11e8-80c0-219cb62997de.png)

# Todo

- [ ] Amend the header image to the same as the homepage
- [ ] Amend the heading size to the same as the homepage
- [ ] Amend the subtitle size to the same as the homepage

**Comment by notthetup** [comment]
This issue was moved to org-arl/unet-blog#9
